export const categoryLookup = {
	spicy: "Spicy",
	seafood: "Seafood",
	vegan: "Vegan",
	vegetarian: "Vegetarian",
	glutenfree: "Gluten-Free",
	dessert: "Dessert",
	drinks: "Drinks",
	pasta: "Pasta",
	soup: "Soup",
	salad: "Salad",
	barbecue: "Barbecue",
	beef: "Beef",
	healthy: "Healthy",
	appetizer: "Appetizer",
	sidedish: "Side Dish",
	quickandeasy: "Quick & Easy",
	mealprep: "Meal Prep",
	mexican: "Mexican",
};
